# Generated by Django 6.0.4 on 2026-06-27 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Klinika nomi')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuridik nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/logos/', verbose_name='Logotip')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Litsenziya raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinikalar',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon +998XXXXXXXXX formatida bo'lishi kerak", regex='^\\+998\\d{9}$')], verbose_name='Telefon')),
                ('is_main', models.BooleanField(default=False, verbose_name='Bosh filialmi')),
                ('opened_at', models.DateField(blank=True, null=True, verbose_name='Ochilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.clinic', verbose_name='Klinika')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.branch', verbose_name='Filial')),
                ('head_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name="Bo'lim boshlig'i")),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10, verbose_name='Xona raqami')),
                ('name', models.CharField(max_length=255, verbose_name='Xona nomi')),
                ('room_type', models.CharField(choices=[('consultation', 'Qabul xonasi'), ('laboratory', 'Laboratoriya'), ('surgery', 'Operatsiya xonasi'), ('ward', 'Palata'), ('procedure', 'Protsedura xonasi')], default='consultation', max_length=20, verbose_name='Xona turi')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='Qavat')),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Sig'im")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organizations.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('clinic',), name='unique_main_branch_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('department', 'number'), name='unique_room_number_per_department'),
        ),
    ]
