# Generated by Django 6.0.4 on 2026-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Bosh bino'),
        ),
    ]
