# Generated by Django 6.0.4 on 2026-06-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('pinfl', models.CharField(blank=True, help_text='14 xonali shaxsiy identifikatsiya raqami', max_length=14, null=True, unique=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Favqulodda holat uchun aloqa shaxsi', max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Umumiy tibbiy eslatmalar', null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Yozuv sarlavhasi (masalan: Dastlabki ko'rik, Nazorat ko'rigi)", max_length=255)),
                ('notes', models.TextField(help_text='Tibbiy yozuvlar, kuzatuvlar')),
                ('attachment', models.FileField(blank=True, help_text="Qo'shimcha fayl (PDF, rasm)", null=True, upload_to='medical_records/')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Tibbiy yozuv',
                'verbose_name_plural': 'Tibbiy yozuvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(help_text="Allergiya sababi (masalan: Penisilin, Yong'oq)", max_length=255)),
                ('severity', models.CharField(choices=[('MILD', 'Yengil'), ('MODERATE', "O'rtacha"), ('SEVERE', "Og'ir"), ('LIFE_THREATENING', 'Hayot uchun xavfli')], default='MILD', max_length=20)),
                ('reaction', models.CharField(blank=True, help_text='Allergik reaktsiya (masalan: Teri toshmasi, Nafas qisilishi)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Allergiya',
                'verbose_name_plural': 'Allergiyalar',
                'ordering': ['severity'],
                'unique_together': {('patient', 'allergen')},
            },
        ),
        migrations.CreateModel(
            name='PatientChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease_name', models.CharField(help_text='Kasallik nomi (masalan: Diabet, Gipertoniya)', max_length=255)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 kodi (masalan: E11, I10)', max_length=10, null=True)),
                ('diagnosed_at', models.DateField(blank=True, help_text="Tashxis qo'yilgan sana", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Hozirda faolmi (davolanmoqdami)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Surunkali kasallik',
                'verbose_name_plural': 'Surunkali kasalliklar',
                'ordering': ['-diagnosed_at'],
                'unique_together': {('patient', 'icd_code')},
            },
        ),
    ]
